name: Regression Test - Numba

on: [push, pull_request]

jobs:
  build:
    runs-on: jpm
    #strategy:
    #    fail-fast: false
    #    matrix:
    #        os: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v3
    - name: Loads modules and activates conda debug
      run: |
        pwd
        ls
        #module load cuda/12 openmpi/4.0_gcc-10
        source ~/.bashrc
        conda init
	source ~/.bashrc
        conda create --name ghaction_temp python=3.11
        conda activate ghaction_temp
        which python
        bash install.sh --hpc
    - name: Debug
      run: |
        source ~/.bashrc
        conda activate ghaction_temp
        pwd
        ls
        lscpu
        nvidia-smi
        pip list
        conda list
    - name: Regression Test - Numba
      run: |
        source ~/.bashrc
        conda activate ghaction_temp
        cd test/regression
        python run.py --mode=numba
